---
title: "The Development of Polarity Subjunctive"
author: "Raquel Montero Estebaranz"
date: "03.04.2024"
output: 
  html_document: 
      toc: true
      toc_float: true
      theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center", warning = FALSE, message = FALSE)

```
```{css, echo=FALSE}
h1,h4 {
  text-align: center;
}
p {
  text-align: justify; 
}
```

## 1. Introduction

This file shows the code used to create the figures of the behavior of the different functions used in Chapter 5 of the thesis entitled "Mood alternations: a synchronic and diachronic study of negated complement clauses". The rest of materials can be found at: https://github.com/Raquel-Montero


Packages that will be used:
```{r}
library(readr)
library(carData)      # for cat package
library(car)          # Anova function
library(dplyr)        # Operations
library(plyr)         # for ddply 
library(ggplot2)      # to use ggplot
library(sjPlot)       # to change the font
library(Matrix)       # for lme4 package
library(lme4)         # to calculate lmer models
library(lmerTest)     # for the p values
library(mgcv)         # for Gam model
library(itsadug)      # for Gam model
library(tidygam)      # for Gam plotting
library(tidymv)       # For Gam plotting: https://www.rdocumentation.org/packages/tidymv/versions/3.4.2
library(ggpubr)
library(LaplacesDemon) #for the function invlogit
```


## 2. Functions: Types of change


```{r}
#Font for the graph:
windowsFonts("Garamond" = windowsFont("Garamond"))

set_theme( base = theme_bw(base_family = 'Garamond'),
  title.size = 1.4,
  axis.title.size = 1.4,
  axis.textsize = 1.1,
  legend.size = 1,
  legend.title.size = 1,
  geom.label.size = 3
)

set_theme( base = theme_classic(base_family = 'Garamond'),
  title.size = 1.4,
  axis.title.size = 1.4,
  axis.textsize = 1.1,
  legend.size = 1,
  legend.title.size = 1,
  geom.label.size = 3
)

logistic <- function(x){(1/(1+exp((x-12)/0.7)))}
inherent.failed <- function(x){(exp(-(x-6.4)/(1)))/(1+exp(-(x-6.4)/(1)))^2}
accidental.failed <- function(x){(exp(-(x-7.7)/(2)))/(1+exp(-(x-5.6)/(1.3)))^2}

# Plot 1:
plot.types.change <- ggplot()+ 
                geom_function(fun=logistic, color = "#4c8c44d9")+ # Sucessful Change
                geom_function(fun=inherent.failed, color = "blue", linetype="dotted")+ # Sucessful Change
                 geom_function(fun=accidental.failed, color = "red", linetype="dashed")+ # Sucessful Change
                labs(title="Linguistic types of change",  # axis
                      x = "Time", 
                       y="Proportion")+
                theme(axis.text.x=element_blank(),
                      axis.ticks.x=element_blank())+
                ylim(0,1)+
                xlim(0,16)+
                annotate("text", x = 3.5, y = 0.8, 
                         label = "Accidental Failed Change", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/2.5,
                         color="red"
                         )+
               annotate("text", x = 6.5, y = 0.3, 
                         label = "Inherent Failed Change", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/2.5,
                         color="blue"
                        )+
              annotate("text", x = 12.5, y = 0.9, 
                         label = "Successful Change", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/2.5,
                         color="darkgreen"
                        )

  
plot.types.change


```
```{r}
ggsave(plot.types.change, file="TypeChanges.png", width = 8, height = 5)
```


## 3. Logistic: 

```{r}

windowsFonts("Garamond" = windowsFont("Garamond"))

set_theme( base = theme_bw(base_family = 'Garamond'),
  title.size = 1.4,
  axis.title.size = 1.4,
  axis.textsize = 1.1,
  legend.size = 1,
  legend.title.size = 1,
  geom.label.size = 3
)

set_theme( base = theme_classic(base_family = 'Garamond'),
  title.size = 1.6,
  axis.title.size = 1.6,
  axis.textsize = 1.3,
  legend.size = 1.2,
  legend.title.size = 1.2,
  geom.label.size = 3
)

logistic1 <- function(x){(1/(1+exp((x-1500)/100)))}
logistic2 <- function(x){(1/(1+exp((x-1500)/50)))}
logistic3 <- function(x){(1/(1+exp((x-1500)/10)))}

plot.logistic1 <- ggplot()+ 
                geom_function(fun=logistic1, color = "#4c8c44d9")+ # Sucessful Change
                geom_function(fun=logistic2, color = "red")+ # Sucessful Change
                geom_function(fun=logistic3, color = "blue")+ # Sucessful Change
                labs(title="",  # axis
                      x = "Time", 
                       y="Proportion Mood (1=ind, 0=subj)")+
                ylim(0,1)+
                xlim(1000,2000)+
                annotate("text", x = 1700, y = 0.8, 
                         label = "s'= 50; s = 0.02", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                         )+
               annotate("text", x = 1700, y = 0.9, 
                         label = "s'= 10 ; s = 0.1", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )+
              annotate("text", x = 1730, y = 0.7, 
                         label = "s'=100; s = 0.001", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                        )

  
plot.logistic1

# A change with s'=100 years  would take 1000 years to complete. That is every 100 years there is 10% less of indicative.
# A change with an s'= 50 would take 500 years to complete. That is every 50 years there is 10% less of indicative. 
# A change with an s'= 10 would take 100 years to complete. That is every 10 years there is 10% less of indicative. 

logistic4 <- function(x){(1/(1+exp((x-1700)/50)))}
logistic5 <- function(x){(1/(1+exp((x-1500)/50)))}
logistic6 <- function(x){(1/(1+exp((x-1300)/50)))}


plot.logistic2 <- ggplot()+ 
                geom_function(fun=logistic4, color = "#4c8c44d9")+ # Sucessful Change
                geom_function(fun=logistic5, color = "red")+ # Sucessful Change
                geom_function(fun=logistic6, color = "blue")+ # Sucessful Change
                labs(title="",  # axis
                      x = "Time", 
                       y="Proportion Mood (1=ind, 0=subj)")+
                ylim(0,1)+
                xlim(1000,2000)+
                annotate("text", x = 1370, y = 0.55, 
                         label = "k=1500", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                         )+
               annotate("text", x = 1100, y = 0.55, 
                         label = "k=1300", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )+
              annotate("text", x = 1600, y = 0.55, 
                         label = "k=1700", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                        )+
            annotate("text", x = 1800, y = 0.7, 
                      label = "Tipping point", 
                      family= theme_get()$text[["family"]],
                      size= theme_get()$text[["size"]]/1.5,
                      color="black"
                                  )+
            geom_hline(yintercept=0.5, linetype="dashed", color = "black")+
            geom_segment(aes(x = 1500, y = 0, xend = 1500, yend = 0.5), linetype="dashed")+
            geom_segment(aes(x = 1300, y = 0, xend = 1300, yend = 0.5), linetype="dashed")+
             geom_segment(aes(x = 1700, y = 0, xend = 1700, yend = 0.5), linetype="dashed")+
            annotate("segment", x = 1800, y = 0.65, xend = 1700, yend = 0.5,
                     arrow = arrow(type = "closed", length = unit(0.02, "npc")))

  
plot.logistic2

logistic7 <- function(x){(1/((1/0.5)+exp((x-1500)/50)))}
logistic8 <- function(x){(1/((1/0.75)+exp((x-1500)/50)))}
logistic9 <- function(x){(1/((1/1)+exp((x-1500)/50)))}

plot.logistic3 <- ggplot()+ 
                geom_function(fun=logistic7, color = "#4c8c44d9")+ # Sucessful Change
                geom_function(fun=logistic8, color = "red")+ # Sucessful Change
                geom_function(fun=logistic9, color = "blue")+ # Sucessful Change
                labs(title="",  # axis
                      x = "Time", 
                       y="Proportion Mood (1=ind, 0=subj)")+
                ylim(0,1)+
                xlim(1000,2000)+
                annotate("text", x = 1600, y = 0.75, 
                         label = "m=0.7", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                         )+
               annotate("text", x = 1600, y = 1, 
                         label = "m=0.9", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )+
              annotate("text", x = 1600, y = 0.50, 
                         label = "m=0.5", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                        )

  
plot.logistic3



combined.logistic <- ggarrange(plot.logistic1,plot.logistic2,plot.logistic3,ncol = 3)


```


```{r}
ggsave(combined.logistic, file="logistic-parameters.png",width = 16, height = 5)
```



## 4. Laplace function:

```{r}

set_theme( base = theme_classic(base_family = 'Garamond'),
  title.size = 1.6,
  axis.title.size = 1.6,
  axis.textsize = 1.3,
  legend.size = 1.2,
  legend.title.size = 1.2,
  geom.label.size = 3
)

laplace1 <- function(x){1*exp(-abs(x-1500)/100)}
laplace2 <- function(x){0.7*exp(-abs(x-1500)/100)}
laplace3 <- function(x){0.4*exp(-abs(x-1500)/100)}

plot.laplace1 <- ggplot()+ 
                 geom_function(fun=laplace1, color = "#4c8c44d9")+
                 geom_function(fun=laplace2, color = "red")+
                geom_function(fun=laplace3, color = "blue")+
                 labs(title="",  # axis
                      x = "Time", 
                      y="Proportion Mood (1=ind, 0=subj)")+
                  ylim(0,1)+
                 xlim(1000,2000)+
                annotate("text", x = 1700, y = 0.9, 
                         label = "q = 1", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                         )+
               annotate("text", x = 1700, y = 0.8, 
                         label = "q = 0.7", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                        )+
              annotate("text", x = 1700, y = 0.7, 
                         label = "q = 0.4", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )
                

plot.laplace1

# The t0 parameter:

laplace4 <- function(x){1*exp(-abs(x-1300)/100)}
laplace5 <- function(x){1*exp(-abs(x-1500)/100)}
laplace6 <- function(x){1*exp(-abs(x-1700)/100)}

plot.laplace2 <- ggplot()+ 
                 geom_function(fun=laplace4, color = "#4c8c44d9")+
                 geom_function(fun=laplace5, color = "red")+
                geom_function(fun=laplace6, color = "blue")+
                 labs(title="",  # axis
                      x = "Time", 
                      y="Proportion Mood (1=ind, 0=subj)")+
                  ylim(0,1)+
                 xlim(1000,2000)+
                annotate("text", x = 1100, y = 0.9, 
                         label = "t0 = 1300", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                         )+
               annotate("text", x = 1500, y = 0.9, 
                         label = "t0 = 1500", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                        )+
              annotate("text", x = 1900, y = 0.9, 
                         label = "t0 = 1700", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )
                

plot.laplace2

## S' parameter: 

laplace7 <- function(x){1*exp(-abs(x-1500)/100)}
laplace8 <- function(x){1*exp(-abs(x-1500)/400)}
laplace9 <- function(x){1*exp(-abs(x-1500)/10)}

plot.laplace3 <- ggplot()+ 
                 geom_function(fun=laplace7, color = "#4c8c44d9")+
                 geom_function(fun=laplace8, color = "red")+
                geom_function(fun=laplace9, color = "blue")+
                 labs(title="",  # axis
                      x = "Time", 
                      y="Proportion Mood (1=ind, 0=subj)")+
                  ylim(0,1)+
                 xlim(1000,2000)+
                annotate("text", x = 1800, y = 0.8, 
                         label = "s'=100", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="darkgreen"
                         )+
               annotate("text", x = 1800, y = 0.9, 
                         label = "s'= 400", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="red"
                        )+
              annotate("text", x = 1800, y = 0.7, 
                         label = "s'=10", 
                         family= theme_get()$text[["family"]],
                          size= theme_get()$text[["size"]]/1.5,
                         color="blue"
                        )
                

plot.laplace3


#combining the plots: 
combined.laplace <- ggarrange(plot.laplace1,plot.laplace2,plot.laplace3, ncol = 3)



```
```{r}
ggsave(combined.laplace, file="laplace-parameters.png", width = 16, height = 5)
```


