---
title: "The Development of Polarity Subjunctive"
author: "Raquel Montero Estebaranz"
date: "03.04.2024"
output: 
  html_document: 
      toc: true
      toc_float: true
      theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align="center", warning = FALSE, message = FALSE)

```
```{css, echo=FALSE}
h1,h4 {
  text-align: center;
}
p {
  text-align: justify; 
}
```

## 1. Introduction

This file shows the code used to analyze the data that appears in Chapter 6 Section 6.1.2 of the thesis entitled "Mood alternations: a synchronic and diachronic study of negated complement clauses". The rest of information can be found at: https://github.com/Raquel-Montero


The following are the packages that will be used:
```{r}
library(readr)
library(readxl)
library(carData)                                    # for cat package
library(car)                                        # Anova function
library(dplyr, warn.conflicts = FALSE)              # Operations
library(plyr)
library(ggplot2)                                    # to use ggplot
suppressPackageStartupMessages(library(sjPlot))     # to change the font
library(Matrix)                                     # for lme4 package
library(lme4)                                       # to calculate lmer models
library(lmerTest, warn.conflicts = FALSE)           # for the p values
```

## 2. Data

```{r}
#Importing the data sets: 

data2 <- read_csv("DiachronySubjunctive.csv", 
                  show_col_types = FALSE,
                  locale = locale(encoding =  "ISO-8859-1"))


ex.data2 <- subset(data2, 
                     Mverbclass!="Na"& # not one of the four verbs
                     Emood !="Na" & 
                     Emood !="NA" &
                     Emood !="inf" &
                     MClauseType=="noninterrogative" &
                     MClauseType2!="Na"&
                     MClauseType2!="declarative"&
                     EClauseType=="unambiguous"
                   )

# Changing the indicative to 1 and subjunctive to 0:
ex.data2$Emood2 <- ifelse(ex.data2$Emood == "subj", 0, 1)
# Converting the into a numeric value:
ex.data2$Emood2 <- as.numeric(as.character(ex.data2$Emood2))

#changing names of values so that they are better for plotting: 
ex.data2$Mverbtype2 <- ifelse(ex.data2$Mverbclass == "factive", "semi-factive", "non-factive")
ex.data2$Construction <- ifelse(ex.data2$Construction == "1st present", "1st present (A)", "other (B)")



```
## 3. Plotting the data

```{r}
# calculate the mean per period, verb type and matrix clause type:
plot.data <- ddply(ex.data2, .(Period,MClauseType2, Mverbclass),
                          summarize, 
                          mean = mean(as.numeric(as.character(Emood2)), na.rm = T),
                          n = sum(!is.na(as.numeric(as.character(Emood2))))
                          )

#Font for the graph:
windowsFonts("Garamond" = windowsFont("Garamond"))

set_theme( base = theme_bw(base_family = 'Garamond'),
  title.size = 1.4,
  axis.title.size = 1.4,
  axis.textsize = 1.1,
  legend.size = 1,
  legend.title.size = 1,
  geom.label.size = 3
)

# Plot 1:
plot.data$Period <- as.factor(plot.data$Period) # Period as factor

mood.verb.class <- ggplot()+  
                geom_point(data=plot.data, 
                           aes(Period, mean, size = n, color=MClauseType2))+ #main data 
                facet_wrap(~Mverbclass, ncol=2)+ # divide into facets
                scale_size_area(max_size=13,limits=c(1,800))+  # controls the maximum side of the points.
                labs(title="Proportion Mood: not V(subj) that p(ind/subj)",  # axis
                      x = " ", 
                       y="Mood Proportion (1=ind,0=subj)")+
                scale_color_manual(values=c("#ffbf00", "gray" ))+ # colors
                labs(size="size", colour="Construction")+ # labels legends
                ylim(0,1)
  
mood.verb.class
```
```{r}
ggsave(mood.verb.class, file="verb-class-subjunctive.png", width = 8, height= 4)
```


 







